site_name: RMA Kinetics Documentation
theme:
  name: "material"
  palette:
    primary: white
    accent: blue
  theme:
    features:
      - content.code.copy
extra:
  homepage: /
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            force_inspection: true
            heading_level: 3
            inherited_members: true
            members_order: source
            show_bases: false
            show_if_no_docstring: true
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - search
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/szablowskilab/rma-kinetics
repo_name: szablowskilab/rma-kinetics
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - "index.md"
  - API Reference:
      - Models:
          - "api/models/constitutive.md"
          - "api/models/tetoff.md"
          - "api/models/chemogenetic.md"
          - "api/models/force.md"
          - "api/models/abstract.md"
          - Dox:
              - "api/models/dox/model.md"
              - "api/models/dox/config.md"
          - CNO:
              - "api/models/cno/model.md"
              - "api/models/cno/config.md"
      - "api/solution.md"
      - "api/units.md"
