from rma_kinetics.units import Time, Concentration

# Units
CONCENTRATION = Concentration.nanomolar
TIME = Time.hours

# Simulation configuration
T0 = 0
T1 = 504
FS = 1
DT0 = 0.1
INIT_BRAIN_RMA = 0
INIT_PLASMA_RMA = 0
MOUSE_WEIGHT = 0.03

# RMA rates
RMA_PROD_RATE = 5e-3
RMA_RT_RATE = 0.6
RMA_DEG_RATE = 7e-3

# Tet-Off params
DOX_HYCLATE_PERCENT = 0.87
DOX_VEHICLE_INTAKE_RATE = 1.875e-4
DOX_BIOAVAILABILITY = 0.9
DOX_VEHICLE_DOSE = 40 * DOX_HYCLATE_PERCENT
DOX_ABSORPTION_RATE = 0.8
DOX_ELIMINATION_RATE = 0.2
DOX_BRAIN_TRANSPORT_RATE = 0.2
DOX_PLASMA_TRANSPORT_RATE = 0.1
DOX_PLASMA_VD = 0.02
DOX_KD = 10
DOX_T0 = 0
DOX_T1 = 48

# tTA params
TTA_PROD_RATE = 10
TTA_DEG_RATE = 1
TTA_KD = 1
LEAKY_RMA_PROD_RATE = 5e-5
